### ISSUE TITLE
Crash in App

### ISSUE THREAD

**Issue by IgorGanapolsky** [Nimrodda/dagger-androidinjector#4]
Hello,
when I run your sample, I get the following crash:
> 03-05 10:55:09.759 5117-5117/org.codepond.daggersample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.codepond.daggersample, PID: 5117
    java.lang.RuntimeException: Unable to create application org.codepond.daggersample.App: java.lang.NullPointerException: Attempt to invoke interface method 'void dagger.android.AndroidInjector.inject(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void dagger.android.AndroidInjector.inject(java.lang.Object)' on a null object reference
        at dagger.android.DaggerApplication.injectIfNecessary(DaggerApplication.java:78)
        at dagger.android.DaggerApplication.onCreate(DaggerApplication.java:53)
        at org.codepond.daggersample.App.onCreate(App.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

Please advise,
Igor

**Comment by Nimrodda** [comment]
Can you try with latest from `master` branch?
What device and API level are you testing against?
